server:
  port: 8080
  contextPath: /ActivityTracker
  
spring:
  datasource:
    url: jdbc:mysql://localhost/activity_tracker
    username: personivsu
    password: 93rs0n1v
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf.cache: false
  mail:
    host: mail.emailsrvr.com
    port: 587
    username: jerico.grijaldo@personiv.com
    password: Welcome@2017
    properties: 
      mail: 
        debug: true
        transport:
          protocol: smtp
        smtp: 
          auth: true
          starttls:
            enable: true
            required: true            
    protocol: smtp

jwt:
  client: tracker-client
  secret: secret
  expiration: 604800
      
security:
  basic:
    enabled: false
    

